2026-06-21 11:55:01

diff --git a/bin_scripts/brewup b/bin_scripts/brewup
--- a/bin_scripts/brewup
+++ b/bin_scripts/brewup
@@ -4,10 +4,10 @@ TEXTCOLOR1='\033[1;33m'
 TEXTCOLOR2='\033[1;34m'
 TEXTCOLOR3='\033[1;30m'
 RESET='\033[0m'
-# printf "${TEXTCOLOR2}mas upgrade..\n"
-# mas upgrade
+
 printf "${TEXTCOLOR1}brew update..\n"
 brew update
+
 BREW_REPO_DIR="$(brew --repo)"
 if [ -d "$BREW_REPO_DIR/.git" ]; then
   printf "Checking for merge conflicts..\n"
@@ -30,36 +30,97 @@ if [ -d "$BREW_REPO_DIR/.git" ]; then
   fi
   cd "$ORIG_DIR" || exit
 fi
+
 printf "${TEXTCOLOR1}brew upgrade..\n"
-# brew upgrade --greedy
-yes | brew upgrade --greedy
-#brew upgrade $(brew outdated --quiet) # for sqlite : not necessary and yeah... fuck it...
+brew upgrade --greedy < /dev/null
+
 printf "${TEXTCOLOR1}brew cleanup..\n"
 brew cleanup
+
 printf "${TEXTCOLOR1}brew doctor..\n"
 brew doctor
+
 printf "${RESET}"
 
-### RIGHT NOW IT DOESN'T WOTK: Purchase of this item is not
-#                              currently available
-#                              This item is being modified. Please try
-#                              again later.
-## works again (deprecated apps had to be removed: radioplayer and perhaps personalausweis app too)
+printf "${TEXTCOLOR2}mas upgrade..\n"
+mas upgrade
+sleep 1
+printf "${TEXTCOLOR3}DONE\n"
 
-      printf "${TEXTCOLOR2}mas upgrade..\n"
-      mas upgrade
-      sleep 1
-      printf "${TEXTCOLOR3}DONE\n"
+# 11:54, 21.06.26, SUN
+
+
+
+
+
+
+
+
+
+
+
+# #!/bin/bash
 
 # TEXTCOLOR1='\033[1;33m'
 # TEXTCOLOR2='\033[1;34m'
-# printf "${TEXTCOLOR2}mas upgrade..\n"
-# mas upgrade
+# TEXTCOLOR3='\033[1;30m'
+# RESET='\033[0m'
+# # printf "${TEXTCOLOR2}mas upgrade..\n"
+# # mas upgrade
 # printf "${TEXTCOLOR1}brew update..\n"
 # brew update
+# BREW_REPO_DIR="$(brew --repo)"
+# if [ -d "$BREW_REPO_DIR/.git" ]; then
+#   printf "Checking for merge conflicts..\n"
+#   ORIG_DIR=$(pwd)
+#   cd "$BREW_REPO_DIR" || exit
+#   if git status --porcelain | grep -E '^(UU|AA|DD|DU|UD) ' > /dev/null; then
+#     printf "Merge conflicts found:\n"
+#     printf "Some files were deleted upstream and are in conflict.\n"
+#     read -p "Auto-resolve and accept the deletions? [y/N] " choice
+#     if [[ "${choice}" =~ ^[Yy]$ ]]; then
+#       printf "Auto-resolving..\n"
+#       git add -u
+#       git commit -m "Auto-resolve deleted file conflicts from upstream."
+#       printf "Conflicts resolved and committed.\n"
+#     else
+#       printf "Skipped conflict resolution: you can resolve manually later.\n"
+#     fi
+#   else
+#     printf "No merge conflicts found.\n"
+#   fi
+#   cd "$ORIG_DIR" || exit
+# fi
 # printf "${TEXTCOLOR1}brew upgrade..\n"
-# brew upgrade --greedy
+# # brew upgrade --greedy
+# yes | brew upgrade --greedy
+# #brew upgrade $(brew outdated --quiet) # for sqlite : not necessary and yeah... fuck it...
 # printf "${TEXTCOLOR1}brew cleanup..\n"
 # brew cleanup
 # printf "${TEXTCOLOR1}brew doctor..\n"
 # brew doctor
+# printf "${RESET}"
+
+# ### RIGHT NOW IT DOESN'T WOTK: Purchase of this item is not
+# #                              currently available
+# #                              This item is being modified. Please try
+# #                              again later.
+# ## works again (deprecated apps had to be removed: radioplayer and perhaps personalausweis app too)
+
+#       printf "${TEXTCOLOR2}mas upgrade..\n"
+#       mas upgrade
+#       sleep 1
+#       printf "${TEXTCOLOR3}DONE\n"
+
+# # TEXTCOLOR1='\033[1;33m'
+# # TEXTCOLOR2='\033[1;34m'
+# # printf "${TEXTCOLOR2}mas upgrade..\n"
+# # mas upgrade
+# # printf "${TEXTCOLOR1}brew update..\n"
+# # brew update
+# # printf "${TEXTCOLOR1}brew upgrade..\n"
+# # brew upgrade --greedy
+# # printf "${TEXTCOLOR1}brew cleanup..\n"
+# # brew cleanup
+# # printf "${TEXTCOLOR1}brew doctor..\n"
+# # brew doctor
